# Site settings
title: "Hotsuyuki Kawanishi blog"
email: ""
description: "Opinions are my own."
baseurl: ""
url: ""
github_username:  "hotsuyuki"
linkedin_username: "hotsuyuki"
twitter_username: "hotsuyuki"

# Build settings
theme: minima
plugins:
  - jekyll-feed
