# Site settings
title: "Hotsuyuki Kawanishi blog"
email: ""
description: "Opinions are my own."
baseurl: ""
url: "https://hotsuyuki.github.io"
github_username:  "hotsuyuki"
linkedin_username: "hotsuyuki"
twitter_username: "hotsuyuki"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: G-WY9BM54ZX4
